spring.application.name=BiNewsian

# Database Configuration
spring.datasource.url=your-database-url
spring.datasource.username=your-database-name
spring.datasource.password=your-database-password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update

# Session Configuration
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false

# Error Pages Configuration
server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-stacktrace=on_param
server.error.include-exception=false
